<?php

namespace MC\PlatformBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * SuggestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMySuggests($user){
        return $this->createQueryBuilder('a')
            ->where('a.recipient = :user')                      // Date de modification antérieure à :date
            ->getQuery()
            ->getResult()
            ;
    }
}
